import Head from "next/head";
import Image from "next/image";
import ReactMarkdown from "react-markdown";

import matter from "gray-matter";

export default function Home({ data, content }) {
  const { title } = data;

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <ReactMarkdown>{content}</ReactMarkdown>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const raw = await import(`../README.md`);

  const { content, data } = matter(raw.default);
  return {
    props: { data, content }, // will be passed to the page component as props
  };
}
